version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
     - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./etc/nginx/sites-enabled:/etc/nginx/sites-enabled
     - ./etc/ssl:/etc/ssl
     - ./var/log/nginx:/var/log/nginx
    ports:
     - 80:80
     - 443:443
